<a href="https://colab.research.google.com/github/Aofarkane/KKU_Data_mining/blob/master/data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np


##numpr array


In [6]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [8]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [9]:
np2[0,:]

array([1, 2])

##HW 6 สร้าง Distance merix ( Euclidean) ของ np2 โดยสร้าง Funtion สำหรับคำนวณ  Euclidean Distance 

In [10]:
import math

In [11]:
def Manhattan(data1,data2):
    distX = abs(data1[0] - data2[0])
    distY = abs(data1[1] - data2[1])
    return distX+distY

In [12]:
Manhattan(np2[0,:],np2[1,:])

5

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
5*np.ones((4,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [16]:
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j]= Manhattan(np2[i,:],np2[j,:])

dist_mat    

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [18]:
np2.shape

(4, 2)

In [19]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [20]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

## Distance of nominal or categorical features

## (extra) python data structure(dictionary)

In [23]:
 d_A ={'a':1,2:3,3:5,'cat':6}

In [24]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [25]:
d_A['cat']

6

In [30]:
d_A['dog']=[1,2,3,4,5]

In [31]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dag': [1, 2, 3, 4, 5], 'dog': [1, 2, 3, 4, 5]}

In [33]:
del d_A['dag']

In [34]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [35]:
import pandas as pd

In [37]:
data_dict={'color':['red','red','green'],
           'status':['single','marrird','single']}

In [38]:
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'marrird', 'single']}

In [39]:
data_pd=pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  marrird
2  green   single

##categorical feature dastance method#1

In [43]:
list(data_pd.iloc[0,:])

['red', 'single']

In [50]:
def meth1_dist(data1,data2):
    N=0
    print (f' data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feature{i} of data1 is {data1[i]},feature{i} os data2 is {data2[i]}')
        if data1[i] != data2[i]:
           N = N+1
           print(f'{data1[i]} is not equal {data2[i]} : update({N})')
        else:
            print(f' {data1[i]} is equal {data2[i]}')
    return N/len(data1)

In [51]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

 data1 is ['red', 'single'] and data2 is ['red', 'marrird']
feature0 of data1 is red,feature0 os data2 is red
 red is equal red
feature1 of data1 is single,feature1 os data2 is marrird
single is not equal marrird : update(1)


0.5

##HW7 calculate distance metrix od data_pd using meth_dist()

##categorical feature dastance method#2

In [54]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_marrird  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [53]:
def binary_sym_dist(data1,data2):
    q = 0
    rs = 0
    t = 0
    for i in range(len(data1)):
        if data1[i] == data2[i]:
           if data1[i] == 1:
              q = q + 1
        else:
            t = t + 1
        if data1[i] != data2[i]:
           rs = rs + 1
    return (rs)/(q+rs+t)

In [55]:
binary_sym_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

0.5

##HW8  calculate distance metrix od data_pd using meth_dist()