<a href="https://colab.research.google.com/github/Aofarkane/KKU_Data_mining/blob/master/data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


##numpr array


In [3]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [9]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [11]:
np2[0,:]

array([1, 2])

##HW 6 สร้าง Distance merix ( Euclidean) ของ np2 โดยสร้าง Funtion สำหรับคำนวณ  Euclidean Distance 

In [15]:
import math

In [16]:
def Manhattan(data1,data2):
    distX = abs(data1[0] - data2[0])
    distY = abs(data1[1] - data2[1])
    return distX+distY

In [17]:
Manhattan(np2[0,:],np2[1,:])

5

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
5*np.ones((4,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [21]:
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j]= Manhattan(np2[i,:],np2[j,:])

dist_mat    

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [25]:
np2.shape

(4, 2)